version: "3.3"
services:

  mydb:
    image: mysql:8
    container_name: mydb
    restart: always
    ports:
    - '33061:3306'
    environment:
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: mykios
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mydb:/var/lib/mysql
    networks:
      - laravel

  php:
    build:
      context: ./php/8.0
      dockerfile: Dockerfile
    image: php
    container_name: php
    restart: unless-stopped
    tty: true
    working_dir: /var/www/
    expose:
      - "9000"
    volumes:
      - ./www:/var/www
    links:
      - mydb
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mydb"
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8004:80
    volumes:
      - ./www:/var/www
      - ./sites:/etc/nginx/conf.d/
    links:
      - php
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./redis:/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
  dockernet:
    external: true
